apiVersion: v1
entries:
  exastro:
  - apiVersion: v2
    appVersion: 2.0.0-beta1
    created: "2023-01-27T16:05:22.536318463+09:00"
    dependencies:
    - condition: exastro-it-automation.enabled
      name: exastro-it-automation
      repository: file://../exastro-it-automation
      version: 1.0.7
    - condition: exastro-platform.enabled
      name: exastro-platform
      repository: file://../exastro-platform
      version: 1.2.0
    description: A Helm chart for Exastro. Exastro is an Open Source Framework for
      digitizing and centrally managing the system configuration.
    digest: 1635b59d2aa1f7caa6d667f96fe1218f43e7b104fb140efa4450a7a68989af64
    home: https://exastro-suite.github.io/
    icon: https://exastro-suite.github.io/docs/asset/logo/exastro/Exastro-logomark2-rgb.svg
    keywords:
    - exastro
    - exastro-platform
    - exastro-it-automation
    maintainers:
    - email: contact@exastro.jp.nec.com
      name: NEC Corporation
    name: exastro
    sources:
    - https://github.com/exastro-suite/exastro-helm
    - https://github.com/exastro-suite/exastro-it-automation
    - https://github.com/exastro-suite/exastro-platform
    type: application
    urls:
    - exastro-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 2.0.0-beta1
    created: "2023-01-27T16:05:22.454847759+09:00"
    dependencies:
    - condition: exastro-it-automation.enabled
      name: exastro-it-automation
      repository: file://../exastro-it-automation
      version: 1.0.7-beta1
    - condition: exastro-platform.enabled
      name: exastro-platform
      repository: file://../exastro-platform
      version: 1.2.0-beta1
    description: A Helm chart for Exastro. Exastro is an Open Source Framework for
      digitizing and centrally managing the system configuration.
    digest: ff128b2fdbe6b5ab18849fed4d13919ea7e07e46f38720b8cfc1d1119a342486
    home: https://exastro-suite.github.io/
    icon: https://exastro-suite.github.io/docs/asset/logo/exastro/Exastro-logomark2-rgb.svg
    keywords:
    - exastro
    - exastro-platform
    - exastro-it-automation
    maintainers:
    - email: contact@exastro.jp.nec.com
      name: NEC Corporation
    name: exastro
    sources:
    - https://github.com/exastro-suite/exastro-helm
    - https://github.com/exastro-suite/exastro-it-automation
    - https://github.com/exastro-suite/exastro-platform
    type: application
    urls:
    - exastro-1.0.0-beta1.tgz
    version: 1.0.0-beta1
  exastro-it-automation:
  - apiVersion: v2
    appVersion: 2.0.3-beta1
    created: "2023-01-27T16:05:22.550137096+09:00"
    description: A Helm chart for Exastro IT Automation. Exastro IT Automation is
      an Open Source Framework for digitizing and centrally managing the system configuration.
    digest: dd82e08ee75299d5d3997d839191491c4cd28d66b147af426634de94f8aed3ed
    home: https://exastro-suite.github.io/
    icon: https://exastro-suite.github.io/docs/asset/logo/exastro/Exastro-logomark2-rgb.svg
    keywords:
    - exastro
    - exastro-it-automation
    maintainers:
    - email: contact@exastro.jp.nec.com
      name: NEC Corporation
    name: exastro-it-automation
    sources:
    - https://github.com/exastro-suite/exastro-it-automation
    type: library
    urls:
    - charts/exastro-it-automation-1.0.7.tgz
    version: 1.0.7
  exastro-platform:
  - apiVersion: v2
    appVersion: 1.2.0-beta1
    created: "2023-01-27T16:05:22.564363875+09:00"
    description: A Helm chart for Exastro Platform. Exastro Platform is common framework
      for Exastro suite applications.
    digest: c995b7a000ef62ecb57876c824a968e6d8e6c0381c1bd4ef0596ef0f9fb6ed48
    home: https://exastro-suite.github.io/
    icon: https://exastro-suite.github.io/docs/asset/logo/exastro/Exastro-logomark2-rgb.svg
    keywords:
    - exastro
    - exastro-platform
    maintainers:
    - email: contact@exastro.jp.nec.com
      name: NEC Corporation
    name: exastro-platform
    sources:
    - https://github.com/exastro-suite/exastro-platform
    type: library
    urls:
    - charts/exastro-platform-1.2.0.tgz
    version: 1.2.0
generated: "2023-01-27T16:05:22.386450749+09:00"
