---
# Source: ita-by-file-autoclean/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: params-ita-by-file-autoclean
  namespace: exastro
  labels: 
    helm.sh/chart: ita-by-file-autoclean-1.1.0
    app.kubernetes.io/name: ita-by-file-autoclean
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.1.0-beta1"
    app.kubernetes.io/managed-by: Helm
data: 
  EXECUTE_INTERVAL: "10"
  PLATFORM_API_HOST: platform-api.exastro-platform.svc
  PLATFORM_API_PORT: "8000"
---
# Source: ita-by-file-autoclean/templates/deployment.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ita-by-file-autoclean
  namespace: exastro
  labels:
    helm.sh/chart: ita-by-file-autoclean-1.1.0
    app.kubernetes.io/name: ita-by-file-autoclean
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.1.0-beta1"
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: 01 00 * * *
  successfulJobsHistoryLimit: 30
  failedJobsHistoryLimit: 30
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: ita-by-file-autoclean
            app.kubernetes.io/instance: release-name
        spec:
          serviceAccountName: default
          securityContext:
            {}
          initContainers:
            - name: database-alive-check
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
              image: "mariadb:10.9"
              imagePullPolicy: IfNotPresent
              command: ["sh", "-c"]
              args:
                - |
                  #!/bin/bash
                  i=1
                  echo "HOST: ${DB_HOST}"
                  until mysqladmin ping --host=${DB_HOST} --user=${DB_USER} --password=${DB_PASSWORD} --silent; do
                    echo `date`": Can not connect to Database."
                    sleep $i
                    i=$(( i * 2 ))
                  done
                  echo `date`": Completely connect to Database."
                  exit 0
              env:
                - name: DB_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-database
                      key: DB_DATABASE
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-database
                      key: DB_HOST
                - name: DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-database
                      key: DB_PORT
                - name: DB_VENDOR
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-database
                      key: DB_VENDOR
                - name: DB_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ita-secret-ita-database
                      key: DB_ADMIN_PASSWORD
                - name: DB_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: ita-secret-ita-database
                      key: DB_ADMIN_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ita-secret-ita-database
                      key: DB_PASSWORD
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: ita-secret-ita-database
                      key: DB_USER
                - name: CONTAINER_BASE
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-global
                      key: CONTAINER_BASE
                - name: DEFAULT_LANGUAGE
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-global
                      key: DEFAULT_LANGUAGE
                - name: LANGUAGE
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-global
                      key: LANGUAGE
                - name: STORAGEPATH
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-global
                      key: STORAGEPATH
                - name: TZ
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-global
                      key: TZ
          containers:
            - name: ita-by-file-autoclean
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
              image: "alpine"
              imagePullPolicy: IfNotPresent
              env:
                - name: DB_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-database
                      key: DB_DATABASE
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-database
                      key: DB_HOST
                - name: DB_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-database
                      key: DB_PORT
                - name: DB_VENDOR
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-database
                      key: DB_VENDOR
                - name: DB_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ita-secret-ita-database
                      key: DB_ADMIN_PASSWORD
                - name: DB_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: ita-secret-ita-database
                      key: DB_ADMIN_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ita-secret-ita-database
                      key: DB_PASSWORD
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: ita-secret-ita-database
                      key: DB_USER
                - name: CONTAINER_BASE
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-global
                      key: CONTAINER_BASE
                - name: DEFAULT_LANGUAGE
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-global
                      key: DEFAULT_LANGUAGE
                - name: LANGUAGE
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-global
                      key: LANGUAGE
                - name: STORAGEPATH
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-global
                      key: STORAGEPATH
                - name: TZ
                  valueFrom:
                    configMapKeyRef:
                      name: ita-params-ita-global
                      key: TZ
                - name: ENCRYPT_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ita-secret-ita-global
                      key: ENCRYPT_KEY
                - name: EXECUTE_INTERVAL
                  valueFrom:
                    configMapKeyRef:
                      name: params-ita-by-file-autoclean
                      key: EXECUTE_INTERVAL
                - name: PLATFORM_API_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: params-ita-by-file-autoclean
                      key: PLATFORM_API_HOST
                - name: PLATFORM_API_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: params-ita-by-file-autoclean
                      key: PLATFORM_API_PORT
              volumeMounts:
                - name: volume-ita-by-file-autoclean-storage
                  mountPath: /storage
                - name: volume-ita-by-file-autoclean-homedir
                  mountPath: /home/app_user
                - name: volume-ita-by-file-autoclean-tmp
                  mountPath: /tmp
              # livenessProbe:
              #   tcpSocket:
              #     port: 8080
              #   # httpGet:
              #   #   path: /
              #   #   port: 8080
              #   initialDelaySeconds: 5
              #   periodSeconds: 10
              # readinessProbe:
              #   tcpSocket:
              #     port: 8080
              #   # httpGet:
              #   #   path: /
              #   #   port: 8080
              #   initialDelaySeconds: 5
              #   periodSeconds: 10
              resources:
                {}
          volumes:
            - name: volume-ita-by-file-autoclean-storage
              persistentVolumeClaim:
                claimName: pvc-ita-global
            - name: volume-ita-by-file-autoclean-homedir
              emptyDir: {}
            - name: volume-ita-by-file-autoclean-pid
              emptyDir: {}
            - name: volume-ita-by-file-autoclean-socket
              emptyDir: {}
            - name: volume-ita-by-file-autoclean-tmp
              emptyDir: {}
