## Reference: https://github.com/helm/chart-testing-action
name: Linting and Testing
on: pull_request

permissions:
  contents: read

jobs:
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.1 # Also update in publish.yaml

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@v2.3.1
        with:
          # Note: Also update in scripts/lint.sh
          version: v3.7.1

      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
          # ## If executed with debug this won't work anymore.
          # changed=$(ct --config ./.github/configs/ct-lint.yaml list-changed)
          # charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          # if [[ -n "$changed" ]]; then
          #   echo "::set-output name=changed::true"
          #   echo "::set-output name=changed_charts::$charts"
          # fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}
        # run: ct lint --debug --config ./.github/configs/ct-lint.yaml --lint-conf ./.github/configs/lintconf.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          config: .github/configs/kind-config.yaml

      - name: Deploy latest exastro when testing exastro extensions
        if: |
          contains(steps.list-changed.outputs.changed_charts, 'exastro-platform') ||
          contains(steps.list-changed.outputs.changed_charts, 'exastro-it-automation')
        run: |
          helm repo add exastro-dev https://exastro-dev.github.io/charts/
          helm dependency build charts/exastro/
          helm template charts/exastro/ | kubectl apply -f -

      - name: Run chart-testing (install)
        run: ct install --config ./.github/configs/ct-install.yaml
        if: steps.list-changed.outputs.changed == 'true'